//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsemkaBromo
{
    using System;
    using System.Collections.Generic;
    
    public partial class JadwalPenerbangan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JadwalPenerbangan()
        {
            this.PerubahanStatusJadwalPenerbangan = new HashSet<PerubahanStatusJadwalPenerbangan>();
            this.TransaksiHeader = new HashSet<TransaksiHeader>();
        }
    
        public int ID { get; set; }
        public string KodePenerbangan { get; set; }
        public int BandaraKeberangkatanID { get; set; }
        public int BandaraTujuanID { get; set; }
        public int MaskapaiID { get; set; }
        public System.DateTime TanggalWaktuKeberangkatan { get; set; }
        public int DurasiPenerbangan { get; set; }
        public double HargaPerTiket { get; set; }
    
        public virtual Bandara Bandara { get; set; }
        public virtual Bandara Bandara1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerubahanStatusJadwalPenerbangan> PerubahanStatusJadwalPenerbangan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransaksiHeader> TransaksiHeader { get; set; }
        public virtual Maskapai Maskapai { get; set; }
    }
}
