//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foodcourt_latihan_
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuIngredients
    {
        public int ID { get; set; }
        public int MenuI { get; set; }
        public int Ingredient { get; set; }
        public int Unit { get; set; }
        public int Qty { get; set; }
    
        public virtual Ingredients Ingredients { get; set; }
        public virtual Menus Menus { get; set; }
        public virtual Units Units { get; set; }
    }
}
